/* ===== مِراس: دليل المؤشرات ===== */
Object.assign(UI, {
  il_title: ["دليل المؤشرات", "Indicator guide"],
  il_intro: ["كل مؤشر في شارت مِراس: وش يقيس، كيف تقراه، متى ينفع ومتى يخدع، وهل يشتغل على أي سوق.", "Every indicator on the Meras chart: what it measures, how to read it, when it helps and when it misleads, and whether it works on any market."],
  il_what: ["وش يقيس", "What it measures"], il_how: ["كيف تستخدمه", "How to use it"], il_when: ["متى ينفع", "When it helps"], il_trap: ["متى يخدع", "When it misleads"],
  il_cmp: ["الفرق بينها", "How they differ"], il_c1: ["المؤشر", "Indicator"], il_c2: ["النوع", "Type"], il_c3: ["أفضل وقت له", "Best when"], il_c4: ["أضعف وقت له", "Weakest when"],
  il_any: ["هل تشتغل على أي سهم وأي سوق؟", "Do they work on any share and any market?"],
  il_combo: ["كيف تجمع بينها", "How to combine them"], il_count: ["7 مؤشرات", "7 indicators"]
});
const highIn = (sym, a, b) => { const d = practiceSeries(sym); let k = a; for (let i = a; i < b; i++) if (d[i].h > d[k].h) k = i; return k; };
function fibFig() { return miniChart({ sym: "TRN-A", from: 96, n: 64, fib: [lowIn("TRN-A", 98, 116), highIn("TRN-A", 130, 158)] }); }

const IND_LIB = [
  { n: ["المتوسط المتحرك البسيط", "Simple moving average"], c: "SMA", type: ["اتجاه", "Trend"], fig: () => miniChart({ sym: "TRN-A", from: 60, n: 70, sma: [5, 20] }),
    what: ["متوسط إغلاقات آخر عدد من الشموع. يشيل ضجيج الحركة اليومية ويبيّن الجهة العامة.", "The average of the closes of the last several candles. It removes daily noise and shows the general direction."],
    how: ["السعر فوق متوسط صاعد يعني اتجاه صاعد على هذا المدى. فترة 20 للمدى القصير، و50 و200 للمدى الأطول. تقاطع القصير فوق الطويل يعتبره كثير إشارة صعود.", "Price above a rising average means an uptrend on that horizon. Period 20 for the short term, 50 and 200 for longer. Many read the short crossing above the long as bullish."],
    when: ["في الاتجاه الواضح، صاعد أو هابط. يشتغل كدعم متحرك يرتد منه السعر.", "In a clear trend, up or down. It acts as a moving support that price bounces from."],
    trap: ["في المسار العرضي يتقاطع رايح جاي ويعطي إشارات كاذبة. وهو متأخر دائماً: يأكد الحركة بعد ما تبدأ.", "In a range it crosses back and forth and gives false signals. It always lags: it confirms a move after it has begun."], best: ["اتجاه واضح", "Clear trend"], worst: ["مسار عرضي", "Range"] },
  { n: ["المتوسط المتحرك الأسي", "Exponential moving average"], c: "EMA", type: ["اتجاه", "Trend"], fig: () => miniChart({ sym: "TRN-C", from: 95, n: 60, sma: [20] }),
    what: ["متوسط مثل البسيط، لكنه يعطي الشموع الأخيرة وزن أكبر، فيستجيب لتغير السعر أسرع.", "An average like the simple one, but it weights recent candles more heavily, so it responds to price changes sooner."],
    how: ["نفس قراءة المتوسط البسيط. شغّل الاثنين بنفس الفترة على الشارت وشوف كيف الأسي يلف قبل البسيط عند تغير الاتجاه.", "Read it like the simple average. Switch both on with the same period and watch the exponential turn before the simple one when the trend changes."],
    when: ["لما تبي إشارة أبكر، مثل المضاربة القصيرة أو سهم سريع الحركة.", "When you want an earlier signal, such as short-term trading or a fast-moving share."],
    trap: ["سرعته تخليه يعطي إشارات كاذبة أكثر من البسيط. الأسرع ما يعني الأصح.", "Its speed makes it give more false signals than the simple one. Faster does not mean more accurate."], best: ["بداية اتجاه جديد", "Start of a new trend"], worst: ["سوق متذبذب", "Choppy market"] },
  { n: ["مؤشر القوة النسبية", "Relative strength index"], c: "RSI", type: ["زخم", "Momentum"], fig: () => miniChart({ sym: "TRN-B", from: 60, n: 70, pane: "rsi" }),
    what: ["رقم بين 0 و100 يقارن قوة الشموع الصاعدة بقوة الهابطة خلال فترة، غالباً 14. يقيس سرعة الحركة، مو جهتها.", "A number from 0 to 100 comparing the strength of rising candles with falling ones over a period, usually 14. It measures the speed of a move, not its direction."],
    how: ["فوق 70 تشبع شرائي، وتحت 30 تشبع بيعي. استخدمه كتأكيد عند مستوى: تشبع بيعي عند دعم يقوّي فكرة الارتداد.", "Above 70 is overbought, below 30 oversold. Use it as confirmation at a level: oversold at support strengthens the case for a bounce."],
    when: ["في المسار العرضي، لما يتحرك السعر بين دعم ومقاومة.", "In a range, when price moves between support and resistance."],
    trap: ["في الاتجاه القوي يبقى فوق 70 أسابيع والسعر يكمل. التشبع لحاله مو إشارة عكس.", "In a strong trend it stays above 70 for weeks while price continues. An extreme reading alone is not a reversal signal."], best: ["مسار عرضي", "Range"], worst: ["اتجاه قوي", "Strong trend"] },
  { n: ["نطاقات بولنجر", "Bollinger Bands"], c: "BB", type: ["تذبذب", "Volatility"], fig: () => miniChart({ sym: "TRN-B", from: 60, n: 70, bb: true }),
    what: ["ثلاث خطوط: متوسط 20 في النص، وفوقه وتحته خطين يبعدون عنه مرتين الانحراف المعياري. لما السعر يتذبذب بقوة النطاق يتوسع، ولما يهدأ يضيق.", "Three lines: a 20 average in the middle, with a line above and below at two standard deviations. When price swings hard the band widens; when it calms the band narrows."],
    how: ["لمس الخط العلوي يعني السعر مرتفع مقارنة بحركته الأخيرة، والسفلي منخفض. والأهم الانضغاط: نطاق ضيق جداً غالباً يسبق حركة قوية، بس ما يقول لك في أي جهة.", "Touching the upper line means price is high relative to its recent movement; the lower, low. More important is the squeeze: a very narrow band often precedes a strong move, but it does not tell you which way."],
    when: ["في المسار العرضي يشتغل مثل الدعم والمقاومة المتحركة. والانضغاط ينفع في أي وقت كتنبيه إن الهدوء ما بيطول.", "In a range it acts like moving support and resistance. The squeeze is useful at any time as a warning that the calm will not last."],
    trap: ["في الاتجاه القوي السعر يمشي ملاصق للخط العلوي أيام، فبيع كل لمسة للعلوي غلط. الخط مو حاجز.", "In a strong trend price can ride the upper line for days, so selling every touch of it is a mistake. The line is not a wall."], best: ["مسار عرضي وانضغاط", "Range and squeezes"], worst: ["اتجاه قوي", "Strong trend"] },
  { n: ["الماكد", "MACD"], c: "MACD", type: ["زخم واتجاه", "Momentum and trend"], fig: () => miniChart({ sym: "TRN-C", from: 70, n: 80, pane: "macd" }),
    what: ["الفرق بين متوسطين أسيين (12 و26)، ومعه خط إشارة هو متوسط أسي 9 للفرق نفسه. الأعمدة تبيّن المسافة بين الخطين.", "The difference between two exponential averages (12 and 26), with a signal line that is a 9-period exponential average of that difference. The bars show the gap between the two lines."],
    how: ["قطع الماكد لخط الإشارة للأعلى يعتبر إشارة زخم صاعد، وللأسفل هابط. فوق الصفر يعني المتوسط القصير فوق الطويل. والأعمدة اللي تصغر تقول إن الزخم يضعف قبل ما يتقاطعون.", "MACD crossing above its signal line is read as rising momentum; below, falling. Above zero means the short average is above the long one. Shrinking bars say momentum is fading before the lines cross."],
    when: ["في الأسهم اللي تمشي في موجات واضحة، وعلى الإطار اليومي أو أطول.", "On shares that move in clear swings, on the daily timeframe or longer."],
    trap: ["مبني على متوسطات، فهو متأخر مرتين. في المسار العرضي يتقاطع كثير بدون معنى. ومع شموع قليلة ما يظهر: يحتاج 34 شمعة على الأقل عشان يكتمل.", "Built on averages, it lags twice over. In a range it crosses often without meaning. And with few candles it does not appear: it needs at least 34 candles to form."], best: ["موجات واضحة", "Clear swings"], worst: ["مسار عرضي", "Range"] },
  { n: ["الحجم", "Volume"], c: "VOL", type: ["مشاركة", "Participation"], fig: () => miniChart({ sym: "TRN-A", from: 95, n: 60, pane: "vol" }),
    what: ["عدد الأسهم المتداولة في كل شمعة. يقول لك كم واحد شارك في الحركة.", "The number of shares traded in each candle. It tells you how many took part in the move."],
    how: ["قارن حجم الشمعة بمتوسط الشموع اللي قبلها. حركة بحجم أعلى من المعتاد وراها قناعة، وحركة بحجم ضعيف هشة.", "Compare a candle's volume with the average of those before it. A move on above-normal volume has conviction; a move on weak volume is fragile."],
    when: ["عند الاختراقات: اختراق مقاومة بحجم عالي أقوى بكثير من اختراق بحجم عادي.", "At breakouts: a break of resistance on high volume is far stronger than one on normal volume."],
    trap: ["حجم عالي في يوم واحد ممكن يكون صفقة خاصة أو خبر، مو تغير في الاتجاه. والحجم ما يقول لك مين اللي اشترى ومين اللي باع.", "High volume on one day may be a block trade or news, not a change of trend. Volume does not tell you who bought and who sold."], best: ["تأكيد اختراق", "Confirming a breakout"], worst: ["أسهم ضعيفة السيولة", "Illiquid shares"] },
  { n: ["تصحيحات فيبوناتشي", "Fibonacci retracement"], c: "FIB", type: ["مستويات", "Levels"], fig: fibFig,
    what: ["أداة رسم تقسّم حركة سعرية إلى نسب: 23.6% و38.2% و50% و61.8% و78.6%. تبيّن وين ممكن يوقف التصحيح قبل ما تكمل الحركة.", "A drawing tool that divides a price move into ratios: 23.6%, 38.2%, 50%, 61.8% and 78.6%. It shows where a pullback may stop before the move resumes."],
    how: ["في حركة صاعدة: اضغط على القاع ثم القمة. المستويات اللي تطلع هي مناطق دعم محتملة للتصحيح. أشهرها 50% و61.8%. في حركة هابطة اعكس: القمة ثم القاع.", "In an up move: tap the low then the high. The levels that appear are possible support areas for the pullback. The best known are 50% and 61.8%. In a down move reverse it: high then low."],
    when: ["بعد حركة واضحة وقوية بدأت تصحح. وأقوى ما يكون لما يتطابق مستوى فيبوناتشي مع دعم سابق أو متوسط متحرك.", "After a clear, strong move that has started to pull back. It is strongest when a Fibonacci level lines up with a prior support or a moving average."],
    trap: ["النتيجة تتغير حسب أي قاع وقمة تختار، فشخصين يرسمونها مختلف. والمستويات تشتغل لأن كثير يراقبونها، مو لأنها قانون. و50% أصلاً مو من أرقام فيبوناتشي.", "The result changes with which low and high you pick, so two people draw it differently. The levels work because many watch them, not because they are a law. And 50% is not a Fibonacci number at all."], best: ["تصحيح داخل اتجاه", "Pullback within a trend"], worst: ["مسار عرضي بدون حركة واضحة", "A range with no clear move"] }
];

const IL_TEXT = {
  any1: ["نعم. كل هذي المؤشرات حسابات على السعر والحجم فقط، فتشتغل على أي شارت: أسهم سعودية أو أمريكية، عملات، ذهب، أو عملات رقمية، وعلى أي إطار زمني من الدقيقة إلى الشهر. ما فيه مؤشر خاص بسوق معين.", "Yes. All of these are calculations on price and volume only, so they work on any chart: Saudi or US shares, currencies, gold or crypto, and on any timeframe from a minute to a month. No indicator belongs to one market."],
  any2: ["لكن فيه ثلاث فروقات تنتبه لها. الأولى السيولة: المؤشرات تعتمد على إن السعر يعكس تداول كثير، فتضعف في الأسهم قليلة التداول لأن صفقة وحدة تحرك السعر. الثانية الحجم: في سوق العملات ما فيه حجم مركزي حقيقي، فمؤشر الحجم هناك تقريبي. الثالثة قواعد السوق: في السوق السعودي السهم ما يتحرك أكثر من 10% في اليوم، والسوق يقفل نهاية الأسبوع، فتظهر فجوات ما تظهر في سوق يشتغل 24 ساعة.", "But watch three differences. First, liquidity: indicators assume price reflects plenty of trading, so they weaken in thinly traded shares where one trade moves the price. Second, volume: the currency market has no true central volume, so a volume indicator there is approximate. Third, market rules: on the Saudi market a share cannot move more than 10% in a day and the market closes at weekends, so gaps appear that do not in a 24-hour market."],
  combo1: ["لا تجمع مؤشرين من نفس النوع: متوسطين وأسي يقولون لك نفس المعلومة ثلاث مرات. اجمع من أنواع مختلفة: واحد للاتجاه (متوسط 20)، واحد للزخم (RSI)، والحجم للتأكيد، ومستويات ترسمها بيدك. وإذا تعارضوا، فالتعارض نفسه معلومة: السوق ما حسم أمره.", "Do not stack two indicators of the same type: two simple averages and an exponential tell you the same thing three times. Combine different types: one for trend (the 20 average), one for momentum (RSI), volume for confirmation, and levels you draw by hand. If they disagree, the disagreement is itself information: the market has not made up its mind."],
  combo2: ["والمؤشر ما يتوقع. كل المؤشرات تحسب من أسعار صارت، فهي توصف الماضي القريب. قرارك يجي من خطتك: السبب، الوقف، الهدف.", "And an indicator does not predict. Every indicator is computed from prices that already happened, so it describes the recent past. Your decision comes from your plan: reason, stop, target."]
};
function pageIndicators() {
  const dd = (k, v) => "<div><dt>" + esc(t(k)) + "</dt><dd>" + esc(L(v)) + "</dd></div>", para = (k) => "<p>" + esc(L(IL_TEXT[k])) + "</p>";
  return '<div class="wrap"><div class="guide-head"><div class="crumbs"><a href="#guides">' + esc(t("gd_h")) + "</a> / " + esc(t("il_title")) + "</div><h1>" + esc(t("il_title")) + "</h1><p>" + esc(t("il_intro")) + '</p></div><div class="lib">' +
    IND_LIB.map((x) => '<section><div><span class="tag amber">' + esc(L(x.type)) + "</span><h2>" + esc(L(x.n)) + '<small dir="ltr">' + x.c + "</small></h2><dl>" + dd("il_what", x.what) + dd("il_how", x.how) + dd("il_when", x.when) + dd("il_trap", x.trap) + '</dl></div><div class="gs-fig">' + x.fig() + "</div></section>").join("") + "</div>" +
    '<div class="prose-wide" style="padding-block:10px 16px"><h2>' + esc(t("il_cmp")) + '</h2></div><div class="tablewrap"><table><thead><tr>' + ["il_c1", "il_c2", "il_c3", "il_c4"].map((k) => "<th>" + esc(t(k)) + "</th>").join("") + "</tr></thead><tbody>" + IND_LIB.map((x) => "<tr><td><b>" + esc(L(x.n)) + "</b></td><td>" + esc(L(x.type)) + "</td><td>" + esc(L(x.best)) + "</td><td>" + esc(L(x.worst)) + "</td></tr>").join("") + "</tbody></table></div>" +
    '<div class="prose-wide" style="padding-block:26px"><h2>' + esc(t("il_any")) + "</h2>" + para("any1") + para("any2") + "<h2>" + esc(t("il_combo")) + "</h2>" + para("combo1") + para("combo2") + '</div><div class="row" style="justify-content:space-between;padding-block:8px 40px"><a class="btn" href="#guides">' + esc(t("gd_all")) + '</a><a class="btn primary" href="#chart">' + esc(t("gd_go_chart")) + "</a></div></div>";
}
